before:
  hooks:
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64

archives:
- replacements:
    linux: Linux
    amd64: x86_64

changelog:
  sort: asc
